### ISSUE TITLE
Adding touch events?

### ISSUE THREAD

**Issue by juliejernigan** [dnipromv/nonogram#1]
Any chance you have this example as a working game with touch events? Thank you!

**Comment by Nowan** [comment]
As a matter of fact, no, but it's no big deal to provide such an example for you. Just give me a couple of hours)

**Comment by juliejernigan** [comment]
That would be wonderful thank you SO much!!

**Comment by Nowan** [comment]
So I've added basic game template with touch events. Hope you'll find it useful)

**Comment by juliejernigan** [comment]
Hi Mykyta,

Thank you again for building this!  I've been teaching myself corona sdk
for the past 6 months, doing as many online tutorials as I can.  This is
one of my favorite style games that I could not find working source code
for.  I will study your example to learn your thought process behind it.  I
still have a ton to learn but hope in the next few years to become a mobile
game developer.

Sincerely,
Julie Jernigan

**Comment by Nowan** [comment]
Corona is a great tool to begin your journey to mobile game development. My strong advise to you is to not get stuck on tutorials after those 6 month, but to do more coding yourself - it'll have far greater impact on your development skills, and you'll learn a deal faster. Nonogram, actually, is a very good game to start with. You can also implement, let's say, word search puzzle game, that has similar mechanics but different logic, as next excercise. After that, maybe, some simple action game? An so on. Learning is a constant part of being a developer, and I am sure you'll become a good one, since you have that passion. Wish you good luck, and may the Fun be with you)
